language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - npm i --package-lock-only

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy     ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed ahmed3sam/udagram-api-feed:v1
  - docker tag udagram-api-user ahmed3sam/udagram-api-user:v1
  - docker tag reverseproxy     ahmed3sam/reverseproxy:v1
  - docker tag udagram-frontend ahmed3sam/udagram-frontend:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$USERPASSWORD" | docker login -u "$USERNAME" --password-stdin
  - docker push ahmed3sam/udagram-api-feed:v1
  - docker push ahmed3sam/udagram-api-user:v1
  - docker push ahmed3sam/reverseproxy:v1
  - docker push ahmed3sam/udagram-frontend:v1